//---------------------------------------------------------------------------------
//                        Interval HTML file template
//---------------------------------------------------------------------------------

#include <stdlib.h> 

#include "Ver.h"

char *interval[] = {
"<HTML>",
"<HEAD>",
"   <META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">",
"   <META NAME=\"Author\" CONTENT=\"Valentin Emelianov\">",
"   <META NAME=\"GENERATOR\" CONTENT=\"Mozilla/4.05 [en] (Win95; I) [Netscape]\">",
"   <TITLE>",
"@title@",
"</TITLE>",
"</HEAD>",
"<BODY TEXT=\"#000000\" BGCOLOR=\"#FFF0F0\" LINK=\"#FF0000\" VLINK=\"#800080\" ALINK=\"#0000FF\">",
"&nbsp;",
"<A NAME=",
"@label@",
"></A>",
"<CENTER><TABLE BORDER=2 WIDTH=\"90%\" BGCOLOR=\"#FFFFCC\" >",
"<CAPTION><B><BLINK><FONT COLOR=\"#FF6666\"><FONT SIZE=-1>INTERVAL</FONT></FONT></BLINK></B></CAPTION>",
"",
"<TR>",
"<TD BGCOLOR=\"#FFCC00\">",
"<CENTER><B><FONT SIZE=-1>Type</FONT></B></CENTER>",
"</TD>",
"",
"<TD BGCOLOR=\"#FFCC00\">",
"<CENTER><B><FONT SIZE=-1>Level</FONT></B></CENTER>",
"</TD>",
"",
"<TD BGCOLOR=\"#FFCC00\">",
"<CENTER><B><FONT SIZE=-1>Count</FONT></B></CENTER>",
"</TD>",
"",
"<TD BGCOLOR=\"#FFCC00\">",
"<CENTER><B><FONT SIZE=-1>Line</FONT></B></CENTER>",
"</TD>",
"",
"<TD BGCOLOR=\"#FFCC00\">",
"<CENTER><B><FONT SIZE=-1>Expr</FONT></B></CENTER>",
"</TD>",
"",
"<TD BGCOLOR=\"#FFCC00\">",
"<CENTER><B><FONT SIZE=-1>File</FONT></B></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#FFFFCC\">",
"<CENTER><FONT SIZE=-1>",
"@typec@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@levc@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@counc@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@linec@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@exprc@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@filec@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"</TABLE></CENTER>",
"&nbsp;",
"<CENTER><TABLE BORDER=2 WIDTH=\"90%\" BGCOLOR=\"#CCFFFF\" >",
"<TR>",
"<TD BGCOLOR=\"#33CCFF\"><B><FONT SIZE=-1>Processors</FONT></B></TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@proc@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#33CCFF\"><B><FONT SIZE=-1>Efficiency</FONT></B></TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@effic@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#33CCFF\"><B><FONT SIZE=-1>Execution time</FONT></B></TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@exec@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#33CCFF\"><B><FONT SIZE=-1>Total time</FONT></B></TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@total@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#33CCFF\"><B><FONT SIZE=-1>&nbsp;&nbsp;&nbsp; Productive time</FONT></B></TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@ptime@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1><B>CPU = </B>",
"@ptimec@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1><B>SYS = </B>",
"@ptimes@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1><B>I/O = </B>",
"@ptimei@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#33CCFF\"><B><FONT SIZE=-1>&nbsp;&nbsp;&nbsp; Lost time</FONT></B></TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@lost@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#33CCFF\"><B><FONT SIZE=-1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Insufficient parallelism</FONT></B></TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@insuf@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1><B>USR = </B>",
"@iuser@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1><B>SYS = </B>",
"@isyst@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#33CCFF\"><B><FONT SIZE=-1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Communications</FONT></B></TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@comm@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1><B>SYN = </B>",
"@csyn@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#33CCFF\"><FONT SIZE=-1>&nbsp;<B>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Idle time</B></FONT></TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@idle@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#33CCFF\"><B><FONT SIZE=-1>Load imbalance</FONT></B></TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@imbal@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#33CCFF\"><B><FONT SIZE=-1>Synchronization</FONT></B></TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@synch@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#33CCFF\"><B><FONT SIZE=-1>Time variation</FONT></B></TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@vary@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#33CCFF\"><B><FONT SIZE=-1>Overlap</FONT></B></TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@over@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"</TABLE></CENTER>",
"&nbsp;",
"<CENTER><TABLE BORDER=2 WIDTH=\"90%\" BGCOLOR=\"#99FF99\" >",
"<TR BGCOLOR=\"#00CC00\">",
"<TD>",
"<CENTER>&nbsp;</CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><B><FONT SIZE=-1># op</FONT></B></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><B><FONT SIZE=-1>Communications</FONT></B></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><B><FONT SIZE=-1>Real synch</FONT></B></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><B><FONT SIZE=-1>Synch</FONT></B></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><B><FONT SIZE=-1>Variation</FONT></B></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><B><FONT SIZE=-1>Overlap</FONT></B></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#00CC00\">",
"<CENTER><B><FONT SIZE=-1>I/O</FONT></B></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@nopi@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@comi@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@rsynchi@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@synchi@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@varyi@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@overi@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#00CC00\">",
"<CENTER><B><FONT SIZE=-1>Reduction</FONT></B></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@nopr@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@comr@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@rsynchr@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@synchr@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@varyr@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@overr@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#00CC00\">",
"<CENTER><B><FONT SIZE=-1>Shadow</FONT></B></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@nops@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@coms@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@rsynchs@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@synchs@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@varys@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@overs@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"",
"<TR>",
"<TD BGCOLOR=\"#00CC00\">",
"<CENTER><B><FONT SIZE=-1>Remote access</FONT></B></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@nopa@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@coma@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@rsyncha@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@syncha@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@varya@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@overa@",
"</FONT></CENTER>",
"</TD>",
"</TR>",
"<TR>",
"<TD BGCOLOR=\"#00CC00\">",
"<CENTER><B><FONT SIZE=-1>Redistribution</FONT></B></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@nopd@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@comd@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@rsynchd@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@synchd@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@varyd@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@overd@",
"</FONT></CENTER>",
"</TD>",
"</TR>",


"</TABLE></CENTER>",
"@nestbeg@",
"&nbsp;",
"<CENTER><TABLE BORDER=2 WIDTH=\"90%\" BGCOLOR=\"#FFFFCC\" >",
"<CAPTION><B><BLINK><FONT COLOR=\"#FF6666\"><FONT SIZE=-1>NESTED&nbsp; INTERVALS</FONT></FONT></BLINK></B></CAPTION>",
"",
"<TR>",
"<TD BGCOLOR=\"#FFCC00\">",
"<CENTER><B><FONT SIZE=-1>Go</FONT></B></CENTER>",
"</TD>",
"",
"<TD BGCOLOR=\"#FFCC00\">",
"<CENTER><B><FONT SIZE=-1>Type</FONT></B></CENTER>",
"</TD>",
"",
"<TD BGCOLOR=\"#FFCC00\">",
"<CENTER><B><FONT SIZE=-1>Level</FONT></B></CENTER>",
"</TD>",
"",
"<TD BGCOLOR=\"#FFCC00\">",
"<CENTER><B><FONT SIZE=-1>Count</FONT></B></CENTER>",
"</TD>",
"",
"<TD BGCOLOR=\"#FFCC00\">",
"<CENTER><B><FONT SIZE=-1>Line</FONT></B></CENTER>",
"</TD>",
"",
"<TD BGCOLOR=\"#FFCC00\">",
"<CENTER><B><FONT SIZE=-1>Expr</FONT></B></CENTER>",
"</TD>",
"",
"<TD BGCOLOR=\"#FFCC00\">",
"<CENTER><B><FONT SIZE=-1>File</FONT></B></CENTER>",
"</TD>",
"</TR>",
"",
"@nesteds@",
"<TR>",
"<TD BGCOLOR=\"#FFFFCC\">",
"<CENTER><FONT SIZE=-1><A HREF=",
"@url@",
">",
"@go01@",
"</A></FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@type@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@lev@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@coun@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@line@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@expr@",
"</FONT></CENTER>",
"</TD>",
"",
"<TD>",
"<CENTER><FONT SIZE=-1>",
"@file@"
,"</FONT></CENTER>",
"</TD>",
"</TR>",
"@nestedf@",
"</TABLE></CENTER>",
"@nestend@",
"&nbsp;",

"<CENTER><TABLE BORDER CELLPADDING=3 COLS=4 WIDTH=\"30%\" BGCOLOR=\"#CCCCCC\" >",
"<TR>",
"<TD ALIGN=CENTER><B><FONT FACE=\"Arial,Helvetica\"><FONT SIZE=-1><A HREF=",
"@up@",	
">UP</A></FONT></FONT></B></TD>",
"<TD ALIGN=CENTER><B><FONT FACE=\"Arial,Helvetica\"><FONT SIZE=-1><A HREF=",
"@pred@",
">PRED</A></FONT></FONT></B></TD>",
"<TD ALIGN=CENTER><B><FONT FACE=\"Arial,Helvetica\"><FONT SIZE=-1><A HREF=",
"@next@",
">NEXT</A></FONT></FONT></B></TD>",
"<TD ALIGN=CENTER><B><FONT FACE=\"Arial,Helvetica\"><FONT SIZE=-1><A HREF=",
"@home@",
">HOME</A></FONT></FONT></B></TD>",
"</TR>",
"</TABLE></CENTER>",

"<HR SIZE=3  NOSHADE WIDTH=\"100%\">",
"</BODY>",
"</HTML>",
"",
NULL
};