#!/bin/sh

# Uses variables: grep, dvmdir, dvmdirW, PLATFORM, DVMVERS

from_define() {
    DEF_NAME="$1"
    FILE_NAME="$2"
    DESC="$3"
    if [ -f "$FILE_NAME" ]; then
        LINE=$( $grep -e "#define *$DEF_NAME" "$FILE_NAME" | head -1 )
        if [ -n "$LINE" ]; then
            printf '%s\n' "$LINE" | $sed -e "s/#define *$DEF_NAME *[\"]*/    $DESC /" -e 's/["]* *$//'
        fi
    fi
}

echo "====================================================================="
if [ -n "$dvmdirW" ]; then
    echo "DVM-system is installed in $dvmdirW directory for $PLATFORM platform"
else
    echo "DVM-system is installed in $dvmdir directory for $PLATFORM platform"
fi
printf '%s' "DVM-system version is $DVMVERS"
if [ -f "$dvmdir/../revision" ]; then
    REV=`cat "$dvmdir/../revision"`
    printf '%s' ", Revision is $REV"
fi

if [ -f "$dvmdir/bin/dvm_drv" ]; then
   INSTALL_TIME=`ls -l $dvmdir/bin/dvm_drv | awk '{print $6, $7, $8}'`
   printf '%s' ", is installed at '$INSTALL_TIME'"
fi

echo
from_define DVM_VERS_DEF "$dvmdir/rts/src/global1.var" "LibDVM         v."
from_define LIBDVMH_VERSION "$dvmdir/include/dvmhlib_const.h" "LibDVMH        v."
from_define VERS "$dvmdir/cdvm/src/c_dvm.c" "C-DVM          v."
from_define CDVMH_VERSION "$dvmdir/cdvmh/src/c_dvmh.cpp" "C-DVMH         v."
from_define COMPILER_VERSION "$dvmdir/fdvm/include/fdvm_version.h" "Fortran-DVMH   v."
from_define DEBUGGER_VERSION "$dvmdir/rts/src/debug.def" "Debugger       v."
from_define ZLIB_VERSION "$dvmdir/tools/Zlib/include/zlib.h" "Zlib           v."
from_define VER_PPPA "$dvmdir/tools/pppa/src/ver.h" "PPP Analyzer   v."
from_define VER_PRED "$dvmdir/tools/predictor/Presage/Include/Ver.h" "Predictor      v."
echo "====================================================================="
