#ifndef _SYSVAR_INC_
#define _SYSVAR_INC_
/******************/    /*E0000*/

#include "checksum.var"
#include "param.var"
#include "syspar.var"
#include "sysdebug.var"
#include "systrace.var"
#include "trcevent.var"
#include "statist.var"
#include "global1.var"
#include "global2.var"

#include "dynlimit.var"
#include "dyncntrl.var"
#include "cmptrace.var"
#include "cntrlerr.var"


#endif  /* _SYSVAR_INC_ */    /*E0001*/
