/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LibraryImport */

#ifndef _Included_LibraryImport
#define _Included_LibraryImport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LibraryImport
 * Method:    readStat
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jstring JNICALL Java_LibraryImport_readStat
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
