#!/bin/sh

if [ -f demopred.1 ] ; then
    rm demopred.1
fi
export dvmoutfile=demopred.1
export Pred_vis_blk=on
echo "****** Predictor demo jacobi programs ******"
./1pred c jac1d
./1pred f jac
./1pred c jac2d
./1pred f jacas

echo "****** Predictor demo gauss programs ******"
./1pred c gauss_c
./1pred f gausf
./1pred c gauss_wb
./1pred f gauswh

echo "****** Predictor demo redblack programs ******"
./1pred c redb_c
./1pred f redbf

echo "****** Predictor demo jacross sor programs ******"
./1pred c jacross
./1pred f sor

echo "****** Predictor demo tasks programs ******"
./1pred c tsk
./1pred c tsk_ra
./1pred f task2j
./1pred f tasks
./1pred f taskst

echo "****** Predictor demo mgrid programs ******"
./1pred c mgrid

echo "****** Predictor demo HPF programs ******"
./1pred f gaush .hpf
./1pred f jach .hpf
./1pred f redbh .hpf

echo "****** end Predictor demo programs ******"
