#!/bin/sh

clean_and_exit() {
    rm -f jac1d_2_2.*
    rm -f dvmstd.out
    rm -f dvmstd.err
    rm -f test.1
    rm -f test.2
    rm -f testcdvm
    rm -f testfdvm
    exit $1
}

echo "... DVM testing started ..."

TESTPROG=testcdvm.cdv
echo "... $TESTPROG testing  ..."
rm -f test.1
dvmoutfile=test.1 ./dvm ctest "$TESTPROG"
if [ -f dvm.err ] ; then
    clean_and_exit 1
fi
echo "... Comparing $TESTPROG results ..."
../bin/dvmdiff test.1 testcdvm_res
if [ $? != "0" ] ; then
    echo "!!! The $TESTPROG result is different from expected !!!"
    echo "... Do you want to continue? (y/n) ..."
    read ans
    if [ "$ans" != "y" ] ; then
        clean_and_exit 0
    fi
fi
echo "... End of testing $TESTPROG ..."
rm -f test.2
if [ -f ../bin/f_dvm -a -f ../bin/parse ] ; then
    TESTPROG=testfdvm.fdv
    echo "... $TESTPROG testing ..."
    dvmoutfile=test.2 ./dvm ftest $TESTPROG
    if [ -f  dvm.err ] ; then
        clean_and_exit 1
    fi
    echo "... Comparing $TESTPROG results ..."
    ../bin/dvmdiff test.2 testfdvm_res
    if [ $? != "0" ] ; then
        echo "!!! The $TESTPROG result is differ from expected !!!"
        echo "... Do you want to continue? (y/n) ..."
        read ans
        if [ "$ans" != "y" ] ; then
            clean_and_exit 0
        fi
    fi
    echo "... End of testing $TESTPROG ..."
else
    echo "... Fortran DVM is not installed ..."
fi
if [ -f ../bin/predictor ] ; then
    echo "... Predictor testing ..."
    Pred_vis_blk=on ./dvm pred 2 2 jac1d
    if [ -f dvm.err ] ; then
        clean_and_exit 1
    fi
    echo "... Comparing predictor results ..."
    ../bin/dvmdiff jac1d_2_2.html pred_res
    if [ $? != "0" ] ; then
        echo "!!! The predictor result is different from expected !!!"
        clean_and_exit 1
    fi
    echo "... End of predictor testing ..."
else
    echo "... Predictor is not installed ..."
fi

echo "... End of testing DVM ..."
