#!/bin/sh

if [ $1 != "" ] ; then
    rm -f machinelist
    rm -f dvmwork
    rm -f dvm
    rm -f usr.par
fi
rm -f *.c
rm -f *.f
rm -f *.dep
rm -f *.trd
rm -f *.proj
rm -f *_s
rm -f *_p
rm -f cdvm_msg
rm -f *.lst
rm -f jac1d
rm -f jac2d
rm -f gauss_c
rm -f gauss_f
rm -f mgrid
rm -f redb_c
rm -f redb_f
rm -f jac
rm -f *.dat
rm -f *.DAT
rm -f current.par
rm -f pgfile
rm -f *.trc
rm -f *.tr
rm -f *.out
rm -f dvm.err
